spring:
  profiles:
    active:
    - dev
---
server:
  port: 8800

spring:
  profiles: dev #开发环境
  application:
    name: cloud-dev

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
---
server:
  port: 8900

spring:
  profiles: test #测试环境
  application:
    name: cloud-test

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
